/// <autosync enabled="true" />
/// <reference path="dat.gui.js" /> 
/// <reference path="jquery-1.9.0.js" /> 
/// <reference path="jquery-ui.js" /> 
/// <reference path="OrbitControls.js"/>
/// <reference path="stats.js"/>
/// <reference path="three.js" /> 
/// <reference path="APP_INIT.js" /> 
/// <reference path="VA3C_APP.js" /> 